### ISSUE TITLE
Is this a clean-room implementation?

### ISSUE THREAD

**Issue by thbar** [ioquatix/graphviz#1]
My understanding is that `graphviz` is a MIT-licensed re-implementation caused by the fact that `ruby-graphviz` is iself [GPL licensed](https://github.com/glejeune/Ruby-Graphviz/issues/81).

Is `graphviz` a clean-room implementation, which you did without taking parts of `ruby-graphviz`?

Thanks for the clarification!

If I got the history right, I'd vote to add an explanation about that at the top of the readme!

**Comment by ioquatix** [comment]
It was written from scratch and has a different API. It was not based on the design of the existing `ruby-graphviz` nor was any code copied. Does that answer your question?

**Comment by ioquatix** [comment]
Of course, due to the nature of the underlying graphviz data structures, there are obviously high level similarities...

**Comment by thbar** [comment]
This answers my question perfectly. I don't think the obvious high level similarities (since they are both wrappers) is a problem. Thanks! And thanks for tackling this :smile:
